<?php

/**
 * @file
 * Contain all hook functions for Real estate manager Demo module.
 */

/**
 * Implements hook_modules_install().
 *
 * Install fill visualization module fields with demo data.
 */
function re_mgr_demo_modules_installed(array $modules, bool $is_syncing): void {
  if (in_array('re_mgr_visualization', $modules)) {
    $creator_service = \Drupal::service('re_mgr_demo.create_data');
    $creator_service->initVisualizationCreator();
  }
}
